sudo: false
language: python
python:
  - '2.7'
cache:
  directories:
  - $HOME/gcloud/
env:
  global:
    - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client_secrets.json
    - versionlabel=$(git rev-parse --abbrev-ref HEAD)-$(date -u +"%Y%m%d-%H%M%S")
    - secure: "OWPfK1+rO/TKd4UpBNqvp+WBIX0MPdBBjxzOYSP6/CYHj4JI9OhVNex7SP/iCdP6dB5sfcTVDK7RXO7tpvv5sOni49QG1nkX1CSQ+Ugouxr+nbsh1gWVxkgVH6nUZ0OPswCiy2aNy+B3Z9/AMrWmo4U28E5buoKK4VuAmMK7m/D5vUhb9Pv6kVS7HSPmEOUVEz90I0nTSsLzK65gZez+wLvAFH5Tf/ujnJi9rhRjGalImvjicqJ1uK6QTiFsf7skMxcfY7TO+C6L0AzniZGImEsqhZ5YTwqyq1oMwhbXTNGSC22TeUG8Noqx/VzyoccuvOXRBIn+wTyCydKDypBsrONpHQBE/osZ7g8h3+lZ8yai41kSKLNRmIoId4wqmmgy8qC7b3Cw58Ddp3o9tMVMDeoKcX0DGohavOuu1WpatmXqa8pXeW+lumkpI3s4WOFlHXQYKKTNoMiFphYc0pXDclxsMJ/j3vvIHz928u8VR/ffiEvEww6txDThn8PQfq5oVKw3EuMYondEnVmCxIKRHs8qWXZBW11pDpNuOT+T8IxA9LTyAFwjPDJUWWXvNu8IcSHrHFYUBU3u/SD4L/aaIN/UKVqA9QQ00vIRx3m0d6ITzx0m5674MK5S/yXTSTT1+ZdB3pYNsZ/KyEw5BDIo41RwM8pOfPV0i8IZ5RgDiHM="
    - secure: "UU0Hexpg/VArEgZP4ECR/m7DIANbQM6DUfI3tUzzUeRb9uMMmwi9VEnzAYvzrur3A6QmFDsh1fd29O3R1uXJVYkUm3mnsM3/HcUBl0j/9TAllKBU/E6Cy2HddVTWy9tWOx8MKW9AxReJnuPLaQsmyhr7eMm6a9pMJsy7gSHMapte+yzQ2Vvs32DOs88kVG4zQS0GhBiUsuCd5jXOALHtJxyaZh51v0jEB/eYq2mJYXXG05IluKHd300hmcD5nczbaJxSVRmCwEHpC+tpT0oj1fAQkbRKVaUcDljboKHvC2T4FkP8tFBvJ78vWzEyxCaQybSzWTapl7XXEQy6Qv/5/C7N6MzN9SEBWx/pbbwDV7KJb8Pz6AoM7RWWRyj/KlEeLCoApDR/YRjzyVzKfEFMW6AttFtHu8zl+V+5jygJw54CpiTAMG5RwXZlQ3t6c9jJHaaaE2ifpPJ9WaLTu7RhB/aqT5QgaGHblmnG7T8inJgqmR0txZ9CXa8CQ7u4nrLdqGA/cG5SXJK54MZZrhVxqMB3gNW6jO1NGx/yFweJ8UG38NAH8PkFPbVJU38OrmeTe7Ocm8DfRPEimqt3pg3+SbAtVe3wHcjc1QTUWU92WYntgglnOakVifD8tG9dXQ5dSQLeBoEBulscSkxbgTtytYKyPq8V+VmbPWgoyPKfnTs="

    ### define secure env variables for TEST_DB and PROD_DB
    ### example:
    ### travis encrypt TEST_DB='mysql://root:@localhost/migrate_dev'
    # - TEST_DB='mysql://root:@localhost/migrate_test'
    # - PROD_DB='mysql://root:@localhost/migrate_prod'

before_install:
    # ENCRYPT YOUR PRIVATE KEY (If you need authentication)
    # 1. Install and login to the Travis CLI:
    #       $ gem install travis
    #       $ travis login
    # 2. Move your json private key to client_secrets.json
    # 3. Run:
    #       $ travis encrypt-file client_secrets.json --add
    # 4. Commit changes:
    #       $ git add client_secrets.json.enc
    #       $ git commit client_secrets.json.enc .travis.yml

  ## Handles client_secrets.json
  - openssl aes-256-cbc -K $encrypted_e753487dd135_key -iv $encrypted_e753487dd135_iv -in client_secrets.json.enc -out client_secrets.json -d

  ## Download and install google-cloud-sdk
  - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
          mkdir -p $HOME/gcloud &&
          wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud &&
          cd $HOME/gcloud &&
          tar xzf google-cloud-sdk.tar.gz &&
          printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
          cd $TRAVIS_BUILD_DIR;
    fi

  ## update to the latest components
  - gcloud -q components update

  ## use client_secrets.json to auth against gcloud
  - if [ -a client_secrets.json ]; then
          gcloud -q auth activate-service-account --key-file client_secrets.json;
    fi

install:
  ## app specific setup
  - pip install -t lib -r requirements/dev.txt
  - pip install virtualenvwrapper
  - pip install coveralls
  - source virtualenvwrapper.sh
  - add2virtualenv ./lib

  ### Update gcloud project name
  - gcloud config set project russomi-apps

before_script:
  - mysql -e 'create database flasky_appengine_test;'
  - TARGET_DB=$TEST_DB python manage.py db upgrade

script:
  ### Examples:
  # - python testrunner.py $HOME/gcloud/google-cloud-sdk ./tests
  # - coverage run --source . testrunner.py $HOME/gcloud/google-cloud-sdk ./tests
  - coverage run --source . manage.py test

after_success:
  - coveralls
  - gcloud -q preview app deploy app.yaml --version=1
  ### commenting this out since the dedicated ip addy was removed to avoid costs!
  - TARGET_DB=$PROD_DB python manage.py db upgrade
